blank_issues_enabled: false
contact_links:
  - name: Öffentliche Roadmap
    url: https://github.com/Nachtgreif/DxGarden/blob/main/ROADMAP.md
    about: Bereits vorgeschlagene und angenommene Änderungen ansehen
